# Generated by Django 2.2 on 2019-05-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='displays.Display'),
            preserve_default=False,
        ),
    ]
