# Generated by Django 2.2 on 2019-05-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0002_line_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='name',
            new_name='display',
        ),
    ]
