# Generated by Django 2.2 on 2019-05-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0003_auto_20190503_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.Customer'),
        ),
    ]
