# Generated by Django 2.2 on 2019-05-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0006_pollo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollo',
            name='line',
        ),
        migrations.AddField(
            model_name='pollo',
            name='display',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='displays.Display'),
            preserve_default=False,
        ),
    ]
