# Generated by Django 2.2 on 2019-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0007_auto_20190505_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pollo',
        ),
    ]
