# Generated by Django 2.2 on 2019-05-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0008_delete_pollo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollo', models.CharField(max_length=16)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displays.Display')),
            ],
        ),
    ]
