# Generated by Django 2.2 on 2019-05-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0009_pollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollo',
            name='display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displays.Line'),
        ),
    ]
