# Generated by Django 2.2 on 2019-05-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0010_auto_20190505_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pollo',
        ),
    ]
