# Generated by Django 2.2 on 2019-05-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0012_pollo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pollo',
        ),
    ]
