# Generated by Django 2.2 on 2019-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0013_delete_pollo'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='font_size',
            field=models.PositiveSmallIntegerField(choices=[('Small', 8), ('Normal', 12), ('Large', 15)], default=0),
        ),
    ]
