# Generated by Django 2.2 on 2019-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0014_display_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='font_size',
            field=models.PositiveSmallIntegerField(choices=[(8, 'Small'), (12, 'Normal'), (15, 'Large')], default=12),
        ),
    ]
